// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbKZ7dsDhgBhqyCS5FyBQMveq42M5wZWg',
    appId: '1:1073323444628:web:0495a6f9227a63fec3e781',
    messagingSenderId: '1073323444628',
    projectId: 'nawel-25176',
    authDomain: 'nawel-25176.firebaseapp.com',
    storageBucket: 'nawel-25176.firebasestorage.app',
    measurementId: 'G-6VRCN2Z07F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_EBxh-GJ22zO-TH2ASZInmy8AkszXUc',
    appId: '1:1073323444628:android:a90de47eb793d6d9c3e781',
    messagingSenderId: '1073323444628',
    projectId: 'nawel-25176',
    storageBucket: 'nawel-25176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkQMGS4i2t4Robor2sYsCw909SN284xo',
    appId: '1:1073323444628:ios:03fd33fbf1ffa642c3e781',
    messagingSenderId: '1073323444628',
    projectId: 'nawel-25176',
    storageBucket: 'nawel-25176.firebasestorage.app',
    iosBundleId: 'com.example.auvnetTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSkQMGS4i2t4Robor2sYsCw909SN284xo',
    appId: '1:1073323444628:ios:03fd33fbf1ffa642c3e781',
    messagingSenderId: '1073323444628',
    projectId: 'nawel-25176',
    storageBucket: 'nawel-25176.firebasestorage.app',
    iosBundleId: 'com.example.auvnetTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbKZ7dsDhgBhqyCS5FyBQMveq42M5wZWg',
    appId: '1:1073323444628:web:ceccd7a162e83115c3e781',
    messagingSenderId: '1073323444628',
    projectId: 'nawel-25176',
    authDomain: 'nawel-25176.firebaseapp.com',
    storageBucket: 'nawel-25176.firebasestorage.app',
    measurementId: 'G-4N65C52S7D',
  );
}
